name: Security Scan
description: |
  Run Go vulernability scan and Trivy repo scan

  This is designed to be run in CI and provides exit codes when vulnerabilities
  are found. 

runs:
  using: "composite"
  steps:
    - name: Go Vulnerability Check
      id: govulncheck
      uses: golang/govulncheck-action@v1

    - name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@0.23.0
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'table' 
        severity: 'CRITICAL,HIGH'
        exit-code: '1'
      env:
        TRIVY_DB_REPOSITORY: ghcr.io/canonical/comsys-build-tools/trivy-db:2
