name: Security Scan
description: "Run Go vulernability scan and Trivy repo scan"

# TEMP FIX FOR: https://github.com/aquasecurity/trivy-action/issues/389
inputs:
  github-token:
    description: 'GitHub token'
    required: false

runs:
  using: "composite"
  steps:
    - name: Go Vulnerability Check
      id: govulncheck
      uses: golang/govulncheck-action@v1

    - name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@0.23.0
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'table' 
        severity: 'CRITICAL'
        exit-code: '1'
      env:
        # TEMP FIX FOR: https://github.com/aquasecurity/trivy-action/issues/389
        ACTIONS_RUNTIME_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
